### PR TITLE
feat(MMKVWrapper): Added new storage wrapper

### PR DESCRIPTION
**Pull request by Titozzz**
Added storage wrapper for react-native-mmkv.
Storage wrapper already existed for another mmvk lib, but they don't have the same interface

### CODE REVIEW

**Comment by mrousavy** [comment]
🔥🔥🔥🔥

**Review by wodCZ — APPROVED** [review]
Thanks for the PR! The changes look good.

I'll wait with merging for other maintainers. Do we want to maintain another wrapper? I'm fine with that, since it's just few lines.

@wtrocki  @jspizziri

**Comment by wtrocki** [comment]
best effort maintenance is ok

**Comment by wodCZ** [comment]
@Titozzz one more thing. Can you please add `MMKVWrapper` re-export to the [index](https://github.com/apollographql/apollo-cache-persist/blob/master/src/storageWrappers/index.ts)?

https://github.com/apollographql/apollo-cache-persist/blob/44db77df997a595b2037367fea6fa3490c8f409c/src/storageWrappers/index.ts#L1-L6

**Comment by Titozzz** [comment]
done @wodCZ

**Comment by wodCZ** [comment]
Thanks! Released in v0.13.0.

**Pull request merged**
