### PR TITLE
feat(persistor): add an optional persistence mapper function to allow…

### PR DESCRIPTION
**Pull request by jspizziri**
… cache filtration

This MR is based on [the comment here](https://github.com/apollographql/apollo-cache-persist/pull/71#issuecomment-493909027). 

A simple mapping function is backward-compatible, lightweight, and offloads the burden of potential configurations and cache complexities.

### CODE REVIEW

**Comment by jspizziri** [comment]
@wtrocki would love to move this forward if it's headed in the right direction (based on some of the comments you made concerning previous attempts).

**Review by wtrocki — CHANGES_REQUESTED** [review]
Briliant! Elegant! Clever and flexible

I need:

- Add mapper to example
- Add mapper to readme
- [optional] unit test with mapper

With all of that you getting straight merge

**Comment by jspizziri** [comment]
@wtrocki working on it. Hoping to have a revision by today or tomorrow.

**Comment by jspizziri** [comment]
@wtrocki please take a look at the updated example and documentation. For the example, I took inspiration (and copied some code) from [apollo-cache-instorage](https://github.com/TallerWebSolutions/apollo-cache-instorage)'s `@persist` directive approach. I also updated the Readme but TBH I'm not super confident in the organization of what I added. 

LMK what you think.

I can squash all of this once you feel it's in a good place.

**Comment by jspizziri** [comment]
@wtrocki sorry to bother you, but have you had a chance to look at this?

**Comment by wtrocki** [comment]
On holidays. Back in 2 weeks. Wonder why we need so much code in examples?

**Comment by jspizziri** [comment]
@wtrocki no worries, hit me up when you're back. We can take care of it then.

**Comment by jspizziri** [comment]
@wtrocki , there certainly doesn't need to be that much code in the examples, and I can strip it down if you want. My goal was to provide an example that would actually be useful for people to actually use in their projects. As a result, the included example allows for the `directive` approach that the `apollo-cache-instorage` library uses.

If the goal is for it to simply be as minimal as possible rather than as helpful as possible then I can strip it down pretty easily. LMK what direction you want to go.

**Comment by wtrocki** [comment]
I like functional example. more comments and docs needed to example. we can merge this after

**Comment by jspizziri** [comment]
@wtrocki awesome. I just added some more documentation and updated some organization of the example as well. Let me know if there's anything I can do to improve upon anything (or if you want me to squash at this point)!

**Review by wtrocki — APPROVED** [review]

**Comment by jspizziri** [comment]
🎊  Thanks @wtrocki for working with me on this MR! I appreciate the package and the time you spent getting this across the finish line.

If you could lmk once you've released a patch version I'd greatly appreciate it!

**Comment by wtrocki** [comment]
@jspizziri I was impressed when trying your changes locally. This is very elegant and refined PR. Very rare kind in upstream land.
Awesome work. Do you mind me sharing release on twitter (need your twitter handle)?

**Comment by jspizziri** [comment]
@wtrocki 🙇 

Absolutely! Conveniently I'm `@jspizziri`  everywhere (including Twitter).

**Comment by valerybugakov** [comment]
Hey @wtrocki, it seems there were no new releases after this PR merge. Is there a plan to release a new version of the package which this update included?

**Comment by wtrocki** [comment]
I'm testing things on main and doing another bugfix

**Comment by valerybugakov** [comment]
Thanks for the quick response! Let me know if I can help with the release in any way.

**Comment by jspizziri** [comment]
@valerybugakov ,

if you’re in a pinch, I published a package containing the update to use until there’s an official release:

https://www.npmjs.com/package/@5stones/apollo3-cache-persist

If you can wait I’d recommend doing so. I plan on removing the package as soon as there’s an official release.

✌️

**Comment by wtrocki** [comment]
@jspizziri I will give you npm rights. Ping me with user

wtr@redhat.com

**Comment by valerybugakov** [comment]
If the official release is coming in a couple of days, I can wait. 
Thanks for the tip, @jspizziri.

**Comment by jspizziri** [comment]
@valerybugakov just published [v0.11.0](https://github.com/apollographql/apollo-cache-persist/releases/tag/v0.11.0)

**Comment by valerybugakov** [comment]
@jspizziri awesome, thanks!

**Pull request merged**
