### PR TITLE
fix(types): MMKV wrapper - remove undefined, normalize to null

### PR DESCRIPTION
**Pull request by wodCZ**
Today I was testing the MMKV wrapper and another TS issue appeared.

### CODE REVIEW

**Comment by wtrocki** [comment]
I think we should release new version at this point considering that current release is broken

**Comment by wodCZ** [comment]
@wtrocki I agree! Go right for v0.12.0 or 0.12.0-rc?

**Comment by wtrocki** [comment]
0.12.0 please

**Comment by wodCZ** [comment]
Released in [0.12.0](https://github.com/apollographql/apollo-cache-persist/blob/master/CHANGELOG.md#0120-2021-08-12)

**Pull request merged**
