### PR TITLE
fix: persist cache on garbage collection

### LINKED ISSUE #514: Garbage collection isn't working with cache persistance
1. Load `component 1` which call `query 1` which put `object 1` to cache
2. Switch to `component 2` which call `query 2` (now it's active) which put `object 2` to cache.
3. Call `cache.gc()`. Because `query 1` is not longer active, `object 1` will be removed from cache and only `object 2` left.

But because `apollo-cache-persist` doesn't call `persist` on garbage collection, `object 1` will be left on persistence layer and restored back on app reload. It will never be removed from that until we manually call `cache.evict`. It doesn't allow to use automatic garbage collection with `apollo-cache-persist` and require manual cache management for effectiveness.

### PR DESCRIPTION
**Pull request by asvishnyakov**
Closes #514

### CODE REVIEW

**Comment by asvishnyakov** [comment]
@wodCZ @wtrocki May you review, please?

**Comment by asvishnyakov** [comment]
Oh, no, just code, I just see you as most active contributor to this repository 😁

**Comment by asvishnyakov** [comment]
@wtrocki I'm sorry, I misunderstood you first time :) What do you mean by documentation? I added an issue (bug) and this PR just fixes it. I'll be glad to add any information, just give me the right direction please.

**Comment by asvishnyakov** [comment]
@wtrocki I'll be glad if you add a little bit more about which information you asking for.

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
I no longer have maintainer rights in the repository :)

**Comment by jerelmiller** [comment]
Hey @wtrocki apologies for that! I've pinged someone to see if I can get your maintainer rights restored. I think this might have been accidental.

**Comment by jerelmiller** [comment]
@wtrocki you should receive an invitation shortly to get access back to the repo. Apologies again for the mix up!

**Review by wtrocki — APPROVED** [review]

**Comment by wodCZ** [comment]
Hello team,
I've made a few changes to the build scripts during the last package update (mostly got rid of what seemed to be unused, or was using a deprecated package).

I can merge this, do another dependency update, and release this hopefully on the beginning of next week.

**Comment by wtrocki** [comment]
Thank you @wodCZ

**Comment by asvishnyakov** [comment]
@wodCZ Any news?

**Comment by wodCZ** [comment]
@asvishnyakov sorry for the delay, things got busy on my end. Once I get an approve in #516 I should be able to release the new version.

**Pull request closed without merging**
