### PR TITLE
Add information about development version of the package

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
Pushed:
apollo-cache-persist-dev@0.1.1

**Comment by SakrImpargo** [comment]
@wtrocki Can we get a new version of the dev package launched soon?

**Comment by wtrocki** [comment]
This is already published

**Comment by KhaledSakr** [comment]
Does it include the changes from https://github.com/apollographql/apollo-cache-persist/pull/263?

**Comment by wtrocki** [comment]
Yes. I pushed from master that should have it. If there are problems let me know we can release new version

**Pull request merged**
