### PR TITLE
Publish source files

### LINKED ISSUE #455: Warning after upgrading to React Scripts (CRA) 5.0.0
Just after upgrading to CRA v5 the development server logs this error several times:

```bash
WARNING in ./node_modules/apollo3-cache-persist/lib/storageWrappers/LocalForageWrapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '{{PATH}}/node_modules/apollo3-cache-persist/src/storageWrappers/LocalForageWrapper.ts' file: Error: ENOENT: no such file or directory, open '{{PATH}}/node_modules/apollo3-cache-persist/src/storageWrappers/LocalForageWrapper.ts'
 @ ./node_modules/apollo3-cache-persist/lib/storageWrappers/index.js 3:0-37 3:0-37
 @ ./node_modules/apollo3-cache-persist/lib/index.js 4:0-40 4:0-40
 @ ./src/App.tsx 13:0-53 46:4-16
 @ ./src/index.tsx 18:0-24 46:36-39
 ```

- [x] Using LocalForage

### PR DESCRIPTION
**Pull request by bkrausz**
Fixes #455

Verified manually that this resolves the sourcemap errors. I have no preference between this or inline sourcemaps, lmk if you'd prefer that I switch methods.

### CODE REVIEW

**Review by wtrocki — APPROVED** [review]

**Comment by bkrausz** [comment]
Thanks for merging @wtrocki! Would we be able to cut a v0.13.1 to get this out?

**Comment by neopostmodern** [comment]
#455 is absolutely spamming my log output. A release would be extremely helpful.

**Comment by wtrocki** [comment]
Sure. Will do tommorow

**Comment by neopostmodern** [comment]
Thanks @wtrocki ! Will this get published to npm automatically at some point or is further action required?

**Comment by wtrocki** [comment]
Done. Sorry for delay

**Pull request merged**
