### PR TITLE
Update Apollo client to 3.1.5

### PR DESCRIPTION
**Pull request by NaLLiFFuNT**

### CODE REVIEW

**Comment by wtrocki** [comment]
Awesome work @NaLLiFFuNT 

I think the way forward would be to:

- Post status of the work. What is working, challenges etc.
- Make sure that we have continuous integration fixed 
- Agree on the package name (we need different package name for the apollo2 and apollo3
- Merge this PR with all docs changes (I will create tag for the Apollo 2.0 client in case some fixes will be needed in future)
- Drop info on twitter and other channels.

**Comment by ajpaulingalls** [comment]
love to see this merged.  perhaps a major version change would be in order as well.

**Comment by wtrocki** [comment]
I can merge it and release as new package
but not release as the same as I do not have access. 

@ajpaulingalls Have you tried this?

**Comment by ajpaulingalls** [comment]
@wtrocki no, have only looked at the code.  I can fork and merge, but it would be better to update this package since all search results etc. go here.  Is Apollo no longer maintaining this repo?

**Comment by wtrocki** [comment]
Apollo no longer maintains it so we can merge and rename package

**Comment by wtrocki** [comment]
Apollo 3 is current version so this makes sense

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
Done quick app.. Looks like this works nicely

**Comment by wtrocki** [comment]
Released as apollo3-cache-persist

Let me know if that works for you

**Pull request merged**
