### PR TITLE
update examples, fix hooks example in readme

### PR DESCRIPTION
**Pull request by wodCZ**
Based on the issue #412 I've updated the react native example app.

I'm thinking of ~dropping~ simplifying the readme examples (maybe keeping just one with hooks?) in favour of the example app, as the readme one tends to get out of date.

### CODE REVIEW

**Comment by wtrocki** [comment]
+100

**Comment by wodCZ** [comment]
I've also updated the web example, it's mostly the same as the react-native example (the used wrapper and styles are different). While I was there, I updated it's dependencies too.

I've removed the class example and fixed the hooks example and added few links to examples directory where they felt relevant.

Also, the API used in previous examples was terribly unstable (usually took few minutes to boot, then it worked fine for some time), so I replaced it with the Space X api, that doesn't require any API key and is consistently fast.

Finally, I've removed the Reactive Variable example, since it was more confusing than useful. Took me a while to realise it's there to demonstrate it doesn't persist (few others were confused too in the [original issue](https://github.com/apollographql/apollo-cache-persist/issues/361#issuecomment-706402442)). I took a while to check the implementation, and I don't believe it would be possible to add support for RV to this library anytime soon.

image

**Comment by wtrocki** [comment]
Amazing work!

**Review by wtrocki — APPROVED** [review]
Verified. All good

**Pull request merged**
