### PR TITLE
Bump versions and fix types

### PR DESCRIPTION
**Pull request by jamesreggio**
@peggyrayzis, could you merge and cut a release? (I don't have npm publish permissions.)

This the package up to date and resolves the typing issues in #57.

### CODE REVIEW

**Comment by matrunchyk** [comment]
Can this be merged?

**Comment by AntonioAngelino** [comment]
Any news?

**Comment by frederikhors** [comment]
Any news on this?

**Comment by sigfriedCub1990** [comment]
Could someone please merge this PR with the master branch?

**Comment by wtrocki** [comment]
@jamesreggio I will bump packages to recent versions and try this change.

**Comment by wtrocki** [comment]
💯 Thank you so much for contribution. It will take some time to publish all changes as we going thru large backlog of issues. If you guys are blocked by this please try this change by installing a package directly from the Github.

**Pull request merged**
